# -*- coding: utf-8 -*-
"""Figure_1_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjUmdOtuEbN96kpqCu4j3_UZNaSC1Uvz
"""

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP1_AB_5fold_results.csv")

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS
drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)

# FEATURES AND TARGET
X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()

# MODELS
models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}

# 5-FOLD STRATIFIED CV
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP2_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP3_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP4_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP5_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4", "W_5", "V_5"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 W5 V5 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP6_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4", "W_5", "V_5", "W_6", "V_6"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 W5 V5 W6 V6 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP7_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4", "W_5", "V_5", "W_6", "V_6", "W_7", "V_7"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 W5 V5 W6 V6 W7 V7 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP8_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4", "W_5", "V_5", "W_6", "V_6", "W_7", "V_7", "W_8", "V_8"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 W5 V5 W6 V6 W7 V7 W8 V8 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP9_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4", "W_5", "V_5", "W_6", "V_6", "W_7", "V_7", "W_8", "V_8", "W_9", "V_9"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 W5 V5 W6 V6 W7 V7 W8 V8 W9 V9 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

from google.colab import drive
drive.mount("/content/drive")

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# PATHS

INPUT = "/content/drive/MyDrive/research/dataset2_αβ.csv"
OUTDIR = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"
os.makedirs(OUTDIR, exist_ok=True)

OUT = os.path.join(OUTDIR, "CP10_AB_5fold_results.csv")


# LOAD DATA

df = pd.read_csv(INPUT)

print("Original shape:", df.shape)

TARGET_COL = "final_result"


# REMOVE UNWANTED COLUMNS

drop_cols = [
    "id_student",
    "code_module",
    "code_presentation",
    "assessment_grade",
    "VLE_normalized"
]

df = df.drop(columns=[c for c in drop_cols if c in df.columns])


# KEEP ONLY W1 AND V1

grade_cols = [c for c in df.columns if c.startswith("W_") or c.startswith("V_")]
remove_grades = [c for c in grade_cols if c not in ["W_1", "V_1", "W_2", "V_2", "W_3", "V_3", "W_4", "V_4", "W_5", "V_5", "W_6", "V_6", "W_7", "V_7", "W_8", "V_8", "W_9", "V_9", "W_10", "V_10"]]
df = df.drop(columns=remove_grades)

print("Shape after cleaning:", df.shape)


# FEATURES AND TARGET

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()


# MODELS

models = {
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(
        n_estimators=400,
        n_jobs=-1,
        random_state=42
    ),
    "GradientBoosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=600,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=42
    ),
    "NeuralNetwork_MLP": MLPClassifier(
        hidden_layer_sizes=(128, 64),
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
}


# 5-FOLD STRATIFIED CV

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    acc_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
        X_train = X.iloc[train_idx].copy()
        X_test = X.iloc[test_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_test = y.iloc[test_idx].copy()

        num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = [c for c in X_train.columns if c not in num_cols]

        numeric_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])

        categorical_tf = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])

        preprocess = ColumnTransformer([
            ("num", numeric_tf, num_cols),
            ("cat", categorical_tf, cat_cols)
        ])

        pipe = Pipeline([
            ("preprocess", preprocess),
            ("model", clone(model))
        ])

        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)

        acc_scores.append(accuracy_score(y_test, pred))
        precision_scores.append(precision_score(y_test, pred, average="weighted", zero_division=0))
        recall_scores.append(recall_score(y_test, pred, average="weighted", zero_division=0))
        f1_scores.append(f1_score(y_test, pred, average="weighted", zero_division=0))

    results.append({
        "Checkpoint": "CP1",
        "Model": name,
        "Accuracy_mean": np.mean(acc_scores),
        "Accuracy_std": np.std(acc_scores),
        "Precision_mean": np.mean(precision_scores),
        "Precision_std": np.std(precision_scores),
        "Recall_mean": np.mean(recall_scores),
        "Recall_std": np.std(recall_scores),
        "F1_mean": np.mean(f1_scores),
        "F1_std": np.std(f1_scores)
    })

results_df = pd.DataFrame(results)

print("\nResults using dataset + W1 V1 W2 V2 W3 V3 W4 V4 W5 V5 W6 V6 W7 V7 W8 V8 W9 V9 W10 V10 only with 5-fold stratified CV\n")
display(results_df)

results_df.to_csv(OUT, index=False)

print("Saved:", OUT)

import pandas as pd
import os

base_path = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS"

all_results = []

for i in range(1, 11):
    file_path = os.path.join(base_path, f"CP{i}_AB_5fold_results.csv")

    df = pd.read_csv(file_path)

    df["Day_count"] = 26 * i

    df = df.rename(columns={
        "Accuracy_mean": "Validation_accuracy",
        "Precision_mean": "Validation_precision",
        "Recall_mean": "Validation_recall",
        "F1_mean": "Validation_F1"
    })

    all_results.append(df)

merged_df = pd.concat(all_results, ignore_index=True)

OUT_TOP = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS/ML2_AB_5fold_merged.csv"
merged_df.to_csv(OUT_TOP, index=False)

print("Merged file saved:", OUT_TOP)
display(merged_df.head())

selected_models = [
    "XGBoost",
    "RandomForest",
    "NeuralNetwork_MLP",
    "LogisticRegression"
]

filtered_df = merged_df[merged_df["Model"].isin(selected_models)].copy()
filtered_df = filtered_df[["Model", "Day_count", "Validation_F1"]]

OUT_FILTERED = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS/ML2_FINAL_models_5fold.csv"

filtered_df.to_csv(OUT_FILTERED, index=False)

print("Filtered F1 file saved:", OUT_FILTERED)
display(filtered_df.head())

import pandas as pd
import matplotlib.pyplot as plt
import os

df = pd.read_csv(OUT_TOP)
df["Model"] = df["Model"].astype(str)

model_colors = {
    "XGBoost": "blue",
    "RandomForest": "red",
    "NeuralNetwork_MLP": "black",
    "LogisticRegression": "orange",
}

model_markers = {
    "XGBoost": "o",
    "RandomForest": "D",
    "NeuralNetwork_MLP": "P",
    "LogisticRegression": "v",
}

legend_order = [
    "XGBoost",
    "RandomForest",
    "NeuralNetwork_MLP",
    "LogisticRegression",
]


def plot_metric(metric, ylabel, save_dir=None):

    plt.figure(figsize=(10,7))

    for model in legend_order:

        model_data = df[df["Model"] == model].copy()

        if model_data.empty:
            continue

        model_data = model_data.sort_values("Day_count")

        plt.plot(
            model_data["Day_count"],
            model_data[metric],
            marker=model_markers.get(model,"o"),
            color=model_colors.get(model,"black"),
            linewidth=2,
            markersize=8,
            label=model
        )

    plt.xlabel("Temporal Checkpoints", fontsize=26, fontweight="bold", labelpad=20)

    plt.ylabel(ylabel, fontsize=26, fontweight="bold", labelpad=20)

    days = sorted(df["Day_count"].unique())
    cp_labels = [f"$CP_{{{i+1}}}$" for i in range(len(days))]

    plt.xticks(days, cp_labels, fontsize=18)

    plt.ylim(0.65, 0.95)

    plt.yticks([0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95], fontsize=18)

    plt.grid(True, linestyle="--", alpha=0.5)

    plt.legend(fontsize=16, loc="lower right")

    plt.tight_layout()

    if save_dir is not None:
        os.makedirs(save_dir, exist_ok=True)

        filename = metric + "_over_days.eps"

        plt.savefig(
            os.path.join(save_dir, filename),
            format="eps",
            dpi=300
        )

    plt.show()


# Directory to save plots
save_dir = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS/plots_selected_models"


# Plot all metrics
plot_metric("Validation_F1", "F1-Score", save_dir)

plot_metric("Validation_precision", "Precision", save_dir)

plot_metric("Validation_recall", "Recall", save_dir)

plot_metric("Validation_accuracy", "Accuracy", save_dir)

import pandas as pd
import matplotlib.pyplot as plt
import os

df = pd.read_csv(OUT_TOP)
df["Model"] = df["Model"].astype(str)

model_colors = {
    "XGBoost": "blue",
    "RandomForest": "red",
    "GradientBoosting": "green",
    "LogisticRegression": "orange",
    "DecisionTree": "purple",
    "NeuralNetwork_MLP": "black",
}

model_markers = {
    "XGBoost": "o",
    "RandomForest": "D",
    "GradientBoosting": "s",
    "LogisticRegression": "v",
    "DecisionTree": "^",
    "NeuralNetwork_MLP": "P",
}

legend_order = [
    "XGBoost",
    "GradientBoosting",
    "RandomForest",
    "NeuralNetwork_MLP",
    "LogisticRegression",
    "DecisionTree",
]


def plot_metric(metric, ylabel, save_dir=None):

    plt.figure(figsize=(10,7))

    for model in legend_order:

        model_data = df[df["Model"] == model].copy()

        if model_data.empty:
            continue

        model_data = model_data.sort_values("Day_count")

        plt.plot(
            model_data["Day_count"],
            model_data[metric],
            marker=model_markers.get(model,"o"),
            color=model_colors.get(model,"black"),
            linewidth=2,
            markersize=8,
            label=model
        )


    plt.xlabel("Temporal Checkpoints", fontsize=26, fontweight="bold", labelpad=20)

    plt.ylabel(ylabel, fontsize=26, fontweight="bold", labelpad=20)

    days = sorted(df["Day_count"].unique())
    cp_labels = [f"$CP_{{{i+1}}}$" for i in range(len(days))]

    plt.xticks(days, cp_labels, fontsize=18)

    plt.ylim(0.65, 0.95)

    plt.yticks([0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95], fontsize=18)

    plt.grid(True, linestyle="--", alpha=0.5)

    plt.legend(fontsize=16, loc="lower right")

    plt.tight_layout()

    if save_dir is not None:
        os.makedirs(save_dir, exist_ok=True)

        filename = metric + "_over_days.eps"

        plt.savefig(
            os.path.join(save_dir, filename),
            format="eps",
            dpi=300
        )

    plt.show()


# Directory to save plots
save_dir = "/content/drive/MyDrive/research/ML_ALGO/AB_CP_RESULTS/plots_all_models"


# Plot all metrics
plot_metric("Validation_F1", "F1-Score", save_dir)
plot_metric("Validation_precision", "Precision", save_dir)
plot_metric("Validation_recall", "Recall", save_dir)
plot_metric("Validation_accuracy", "Accuracy", save_dir)

